### ISSUE TITLE
some error in readme.md

### ISSUE THREAD

**Issue by ninding** [BorealisAI/ranksim-imbalanced-regression#2]
![image](https://user-images.githubusercontent.com/91425172/197985012-5f648810-434e-4168-a0aa-77149661d980.png)
command of 5 and 6 are same.

**Comment by yugongg** [comment]
Thanks for finding this error! I have corrected the FDS command.

**Comment by ninding** [comment]
在sts-b-dir文件夹下readme.md的命令行还是错的

**Comment by yugongg** [comment]
谢谢！现在也已经更正了
